# Generated by Django 4.2 on 2023-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodline', models.CharField(max_length=255)),
                ('breed_type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('gen', models.CharField(max_length=4)),
                ('horse_type', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('inserted_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('nft_id', models.IntegerField(unique=True)),
                ('offsprings', models.JSONField()),
                ('parents', models.JSONField()),
                ('race_statistic', models.JSONField()),
            ],
        ),
    ]
